/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Core_values_smaller_uv.glb --transform 
Files: ./public/Core_values_smaller_uv.glb [5.36MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/Core_values_smaller_uv-transformed.glb [1.29MB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Core_values_smaller_uv-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Microbial Tenements']} position={[0, 5.599, 0]} />
    </group>
  )
}

useGLTF.preload('/Core_values_smaller_uv-transformed.glb')
