/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Core_values_smaller.glb --transform 
Files: ./public/Core_values_smaller.glb [1.37MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/Core_values_smaller-transformed.glb [58.84KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Core_values_smaller-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Procedural Fantasy Texture.001']} position={[0, 5.599, 0]} />
    </group>
  )
}

useGLTF.preload('/Core_values_smaller-transformed.glb')
