/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/ABOUT.glb --transform 
Files: ./public/ABOUT.glb [1.14MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/ABOUT-transformed.glb [84.86KB] (93%)
*/

import { useLayoutEffect, useRef } from 'react'
import { Center, useGLTF, useHelper } from '@react-three/drei'
// import { PointLightHelper, SpotLightHelper } from 'three'
// import { RectAreaLightHelper } from 'three/examples/jsm/helpers/RectAreaLightHelper.js'
import { useFrame } from '@react-three/fiber'

const host_url = "https://files.creative-directors.com/creative-website/creative25/about_page"
const url = host_url + '/models/about-header-transformed.glb'

export function HeaderText(props) {
  const { nodes, materials } = useGLTF(url)
  const pointLightRef = useRef()
  // const spotLightRef = useRef()
  const centerRef = useRef()
  const rectAreaLightRef = useRef()
  // useHelper(spotLightRef, SpotLightHelper, 'blue')
  // useHelper(rectAreaLightRef, RectAreaLightHelper, 'red')
  // useHelper(pointLightRef, PointLightHelper, 0.5, 'cyan')

  useLayoutEffect(() => {
    if (rectAreaLightRef.current && centerRef.current) {
      rectAreaLightRef.current.target = centerRef.current
    }
  }, [])

  useFrame((state) => {
    if (pointLightRef.current) {
      const t = state.clock.getElapsedTime() / 2
      pointLightRef.current.position.x = -Math.cos(t) * 9
      pointLightRef.current.position.z = Math.sin(t) * 2
    }
  })

  return (
    <group {...props} dispose={null}
      rotation={[0, 0.79, 0]}
    >
      <group scale={2.5}>
        <Center
          rotation={[Math.PI / 2, 0, 0]}
          ref={centerRef}
        >
          <mesh geometry={nodes.Text_projekte.geometry} material={materials.White} position={[0, -0.021, 0]} />
          <mesh geometry={nodes.Bevel.geometry} material={materials['Material.001']} position={[0, -0.142, 0]} />
        </Center>
      </group>

      <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
        <pointLight ref={pointLightRef} position={[0, -0.5, 2]} intensity={1}
          distance={5}
        />

        <rectAreaLight ref={rectAreaLightRef} position={[0, 2, 7]} intensity={10}
          width={20}
          height={2}
        />
      </group>

    </group>
  )
}

useGLTF.preload(url)
