/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/About_terrain_1.glb --transform 
Files: ./public/About_terrain_1.glb [989.2KB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/About_terrain_1-transformed.glb [111.18KB] (89%)
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Terrain(props) {
  const { nodes } = useGLTF('/About_terrain_1-transformed.glb')
  const terrainTexture = useTexture('/Terrain_Material.png')
  terrainTexture.flipY = false

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003.geometry} >
        <meshStandardMaterial map={terrainTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/About_terrain_1-transformed.glb')
useTexture.preload('/Terrain_Material.png')
