/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/About_terrain_1.glb --transform 
Files: ./public/About_terrain_1.glb [989.2KB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/About_terrain_1-transformed.glb [111.18KB] (89%)
*/

import { useGLTF, useTexture } from '@react-three/drei'

const host_url = "https://files.creative-directors.com/creative-website/creative25/about_page"
const url_terrain = host_url + '/models/About_terrain-transformed.glb'
const url_terrain_texture = host_url + '/textures/Terrain_Material.webp'

export function Terrain(props) {
  const { nodes } = useGLTF(url_terrain)
  const terrainTexture = useTexture(url_terrain_texture)
  terrainTexture.flipY = false

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003.geometry} >
        <meshStandardMaterial map={terrainTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload(url_terrain)
useTexture.preload(url_terrain_texture)
