/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/planets.glb --transform 
Files: ./public/planets.glb [332.27KB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/planets-transformed.glb [8.2KB] (98%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import {
  Planet1Material,
  Planet2Material,
  Planet3Material,
  Planet4Material,
  Planet5Material,
} from "./PlanetShaders";

// Determine the model URL based on the environment
const isDevelopment = import.meta.env.DEV;
const localModelUrl = "/planets-transformed.glb";
const remoteModelUrl =
  "https://files.creative-directors.com/creative-website/creative25/glbs/planets-transformed.glb"; // Corrected remote URL if needed
const modelUrl = isDevelopment ? localModelUrl : remoteModelUrl;

console.log(`Loading model from: ${modelUrl}`); // Log which URL is being used

export function Planets(props) {
  const group = useRef();
  const sphere1Ref = useRef();
  const sphere2Ref = useRef();
  const sphere3Ref = useRef();
  const sphere4Ref = useRef();
  const sphere0Ref = useRef();

  const material1Ref = useRef();
  const material2Ref = useRef();
  const material3Ref = useRef();
  const material4Ref = useRef();
  const material5Ref = useRef();

  const { camera } = useThree(); // Get camera instance
  const { nodes, materials } = useGLTF(modelUrl);

  // Keep the billboard effect for spheres
  useFrame((state, delta) => {
    [sphere0Ref, sphere1Ref, sphere2Ref, sphere3Ref, sphere4Ref].forEach(
      (sphereRef) => {
        if (sphereRef.current) {
          // Make spheres look at the camera position
          sphereRef.current.lookAt(camera.position);
        }
      }
    );

    [
      material1Ref,
      material2Ref,
      material3Ref,
      material4Ref,
      material5Ref,
    ].forEach((materialRef) => {
      if (materialRef.current) {
        materialRef.current.uTime += delta;
      }
    });
  });

  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          {/* Empties are just markers, no need to render */}
          {/* <group name="start" position={[-32.842, 4.485, 24.756]} />
          <group name="Empty" position={[-19.471, 1, -4.594]} />
          ... other empties ... */}

          {/* Keep Meshes */}
          <mesh name="Sphere" ref={sphere0Ref} position={[-12.829, 0, -0.945]}>
            <sphereGeometry args={[1, 32, 32]} />
            <planet1Material ref={material1Ref} />
          </mesh>

          <mesh
            name="Sphere001"
            ref={sphere1Ref}
            position={[-1.554, 2.03, 9.812]}
            scale={1.717}
          >
            <sphereGeometry args={[1, 32, 32]} />
            <planet2Material ref={material2Ref} />
          </mesh>

          <mesh
            name="green_planet"
            ref={sphere2Ref}
            position={[3.078, -0.705, -9.599]}
            scale={1.717}
          >
            <sphereGeometry args={[1, 32, 32]} />
            <planet3Material ref={material3Ref} />
          </mesh>

          <mesh
            name="yellow_planet"
            ref={sphere3Ref}
            position={[12.037, -5.171, 2.346]}
            scale={1.557}
          >
            <sphereGeometry args={[1, 32, 32]} />
            <planet4Material ref={material4Ref} />
          </mesh>

          <mesh
            name="Sphere004"
            ref={sphere4Ref}
            position={[21.537, -0.734, -5.153]}
            scale={1.121}
          >
            <sphereGeometry args={[1, 32, 32]} />
            <planet5Material ref={material5Ref} />
          </mesh>
        </group>
      </group>
    </>
  );
}

useGLTF.preload(modelUrl); // Preload the model to improve loading performance
// Preload the model to improve loading performance
