/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Tim_SphereGold.glb --transform 
Files: ./public/Tim_SphereGold.glb [19.47MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/Tim_SphereGold-transformed.glb [617.9KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tim_SphereGold-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CubeStyle001.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/Tim_SphereGold-transformed.glb')
