/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/tunnel_2.glb --transform 
Files: ./public/tunnel_2.glb [10.91MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/tunnel_2-transformed.glb [340.18KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tunnel_2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CubeStyle.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/tunnel_2-transformed.glb')
