/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/tunnel_1.glb --transform 
Files: ./public/tunnel_1.glb [9.72MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/About_page/tunnel_1-transformed.glb [52.96KB] (99%)
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Model(props) {

  const tunnelTexture = useTexture('/Terrain_Material_tube.png')
  tunnelTexture.flipY = false


  const { nodes, materials } = useGLTF('/tunnel_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tunnel.geometry}
        material={tunnelTexture}
        position={[0, -1.263, 0]}
        scale={17}
      />
    </group>
  )
}

useGLTF.preload('/tunnel_1-transformed.glb')
